name: 'Get Project Data'

on:
  schedule:
    - cron: "*/6 * * * *"

env:
  STATSIG_API_KEY: ${{ secrets.STATSIG_API_KEY }}

jobs:
  get-project-data:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: NPM Install
        run: npm ci

      - name: Echoooo
        run: | 
          echo Hello World
          echo ${{ matrix.node-version }}

      - name: Get Project Data
        id: data
        uses: ./action.yml
        with:
          sdk-key: ${{ env.STATSIG_API_KEY }}

      - name: Print Project Data
        run: |
          echo ${{ steps.data.outputs.project-data }}

